import {
  Banana,
  Candy,
  Cherry,
  Clover,
  Crown,
  Dices,
  Fish,
  Gem,
  Ghost,
  Orbit,
  Spade,
  Sun,
  type LucideIcon,
  Sparkles,
  WandSparkles,
} from "lucide-react";

export type Game = {
  slug: string;
  title: string;
  description: string;
  category: "Колесо" | "Слоти" | "Карткова";
  badge: string;
  players: string;
  accent: string;
  icon: LucideIcon;
  image?: string;
  available: boolean;
};

export const games: Game[] = [
  {
    slug: "jungle-wheel",
    title: "Jungle Wheel",
    description: "Крути колесо джунглів, збирай комбо та відкривай сезонні трофеї.",
    category: "Колесо",
    badge: "Грай зараз",
    players: "1 284 онлайн",
    accent: "lime",
    icon: Banana,
    image: "/games/jungle-wheel.png",
    available: true,
  },
  {
    slug: "cherry-club",
    title: "Cherry Club",
    description: "Неонові слоти 5×5 із десятьма лініями та спільним балансом профілю.",
    category: "Слоти",
    badge: "Грай зараз",
    players: "Нова гра",
    accent: "coral",
    icon: Cherry,
    image: "/games/cherry-club.png",
    available: true,
  },
  {
    slug: "moon-mansion",
    title: "Moon Mansion",
    description: "Збирай магічні ключі та проходь кімнати старого маєтку.",
    category: "Слоти",
    badge: "Незабаром",
    players: "У розробці",
    accent: "violet",
    icon: Ghost,
    image: "/games/moon-mansion.png",
    available: false,
  },
  {
    slug: "gem-society",
    title: "Gem Society",
    description: "Карткова колекція, клубні дуелі та косметичні нагороди.",
    category: "Карткова",
    badge: "Незабаром",
    players: "У розробці",
    accent: "gold",
    icon: Gem,
    image: "/games/gem-society.png",
    available: false,
  },
  {
    slug: "neon-seven",
    title: "Neon Seven",
    description: "Яскраві неонові барабани, серії сімок і нічні клубні місії.",
    category: "Слоти",
    badge: "Незабаром",
    players: "У розробці",
    accent: "coral",
    icon: Dices,
    available: false,
  },
  {
    slug: "golden-reef",
    title: "Golden Reef",
    description: "Пірнай за золотими скарбами та збирай колекцію морських талісманів.",
    category: "Слоти",
    badge: "Скоро",
    players: "У розробці",
    accent: "gold",
    icon: Fish,
    available: false,
  },
  {
    slug: "royal-cards",
    title: "Royal Cards",
    description: "Швидкі карткові партії, королівські комбінації та клубні турніри.",
    category: "Карткова",
    badge: "Скоро",
    players: "У розробці",
    accent: "violet",
    icon: Crown,
    available: false,
  },
  {
    slug: "cosmic-spin",
    title: "Cosmic Spin",
    description: "Космічне колесо з орбітальними бонусами та сезонними артефактами.",
    category: "Колесо",
    badge: "Незабаром",
    players: "У розробці",
    accent: "violet",
    icon: Orbit,
    available: false,
  },
  {
    slug: "lucky-garden",
    title: "Lucky Garden",
    description: "Вирощуй щасливу колекцію конюшини й відкривай зелені джекпоти.",
    category: "Слоти",
    badge: "Скоро",
    players: "У розробці",
    accent: "lime",
    icon: Clover,
    available: false,
  },
  {
    slug: "midnight-poker",
    title: "Midnight Poker",
    description: "Стильні нічні роздачі, дружні дуелі та нагороди за серії перемог.",
    category: "Карткова",
    badge: "Незабаром",
    players: "У розробці",
    accent: "coral",
    icon: Spade,
    available: false,
  },
  {
    slug: "desert-fortune",
    title: "Desert Fortune",
    description: "Обертай колесо пустелі й знаходь сонячні реліквії давніх клубів.",
    category: "Колесо",
    badge: "Скоро",
    players: "У розробці",
    accent: "gold",
    icon: Sun,
    available: false,
  },
  {
    slug: "candy-vault",
    title: "Candy Vault",
    description: "Збирай солодкі комбінації та відкривай барвисті косметичні призи.",
    category: "Слоти",
    badge: "Незабаром",
    players: "У розробці",
    accent: "lime",
    icon: Candy,
    available: false,
  },
];

export const dailyRewards = [
  { day: 1, coins: 250, icon: Sparkles },
  { day: 2, coins: 350, icon: Sparkles },
  { day: 3, coins: 500, icon: WandSparkles },
  { day: 4, coins: 650, icon: Sparkles },
  { day: 5, coins: 900, icon: WandSparkles },
  { day: 6, coins: 1_250, icon: Sparkles },
  { day: 7, coins: 2_500, icon: Gem },
];

export const shopItems = [
  {
    slug: "midnight-avatar",
    name: "Midnight Crown",
    type: "Рамка аватара",
    price: 2_400,
    accent: "violet",
  },
  {
    slug: "jungle-trail",
    name: "Jungle Trail",
    type: "Ефект перемоги",
    price: 3_200,
    accent: "lime",
  },
  {
    slug: "coral-card",
    name: "Coral Club",
    type: "Тема профілю",
    price: 1_800,
    accent: "coral",
  },
  {
    slug: "founder-pin",
    name: "Founder Pin",
    type: "Колекційний значок",
    price: 5_000,
    accent: "gold",
  },
];
